name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build MassiveJobs.Core
      run: dotnet build --configuration Release --no-restore --framework netstandard2.0 ./MassiveJobs.Core/MassiveJobs.Core.csproj
    - name: Build MassiveJobs.Core.Tests
      run: dotnet build --configuration Release --no-restore --framework netcoreapp3.1 ./MassiveJobs.Core.Tests/MassiveJobs.Core.Tests.csproj      
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal ./MassiveJobs.Core.Tests/MassiveJobs.Core.Tests.csproj
